agent_type: standard
api_key: sk-ohsIxhcDUF0xwqqmFl1L1niRtEOD9LnvxFGjtjakXennNTzI
base_url: http://35.220.164.252:3888/v1
benchmark: mmlong
config: configs/config_mmlong_mds_output0210.yaml
data_root: /mnt/shared-storage-user/mineru3-share/wangzhengren/PageElement/data/MMLongBench-Doc
defs:
  models:
    ext: rl_ckpt1400
    gen: gemini-2.5-pro
    jdg: sft_ckpt400
  paths:
    docvqa_root: /mnt/shared-storage-user/mineru3-share/wangzhengren/PageElement/data/VisRAG/data/EVisRAG-Test-DocVQA
    finrag_root: /mnt/shared-storage-user/mineru2-shared/jiayu/data/FinRAGBench-V
    mineru: /root/checkpoints/MinerU2.5-2509-1.2B/
    mmlong_root: /mnt/shared-storage-user/mineru3-share/wangzhengren/PageElement/data/MMLongBench-Doc
    qwen_root: /mnt/shared-storage-user/mineru3-share/wangzhengren/JIT-RAG/assets/Qwen
    vidoseek_root: /mnt/shared-storage-user/mineru3-share/wangzhengren/PageElement/data/VisRAG/data/EVisRAG-Test-ViDoSeek
  roots:
    mineru2: /mnt/shared-storage-user/mineru2-shared
    mineru3: /mnt/shared-storage-user/mineru3-share
  secrets:
    ext_key: sk-123456
    gen_key: sk-ohsIxhcDUF0xwqqmFl1L1niRtEOD9LnvxFGjtjakXennNTzI
    jdg_key: sk-123456
  urls:
    extract: http://10.102.244.38:8001/v1
    generate: http://35.220.164.252:3888/v1
    judge: http://10.102.244.38:8003/v1
    mineru: http://10.102.98.181:8000/
    rerank: http://localhost:8000/
embedding_model: /mnt/shared-storage-user/mineru3-share/wangzhengren/JIT-RAG/assets/Qwen/Qwen3-VL-Embedding-8B
evaluation_input: null
evaluation_task: all
extractor_api_key: sk-123456
extractor_base_url: http://10.102.244.38:8001/v1
extractor_model_name: rl_ckpt1400
filter: /mnt/shared-storage-user/mineru2-shared/madongsheng/outputs_0210/results_mmlong_gemini-3-pro-preview/bad_cases/generation_bad_cases.json
finrag_lang: ch
force_rebuild_index: false
generation_input: null
infer_only: false
judger_api_key: sk-123456
judger_base_url: http://10.102.244.38:8003/v1
judger_model_name: sft_ckpt400
limit: null
max_rounds: 5
mineru_model_path: /root/checkpoints/MinerU2.5-2509-1.2B/
mineru_server_url: http://10.102.98.181:8000/
model_name: gemini-2.5-pro
num_threads: 24
output_dir: outputs/mmlong_filter0212_prompt3
reranker_api_base: http://localhost:8000/
reranker_api_key: EMPTY
reranker_model: /mnt/shared-storage-user/mineru3-share/wangzhengren/JIT-RAG/assets/Qwen/Qwen3-VL-Reranker-8B
top_k: 20
trunc_bbox: false
trunc_thres: 0.0
use_crop: true
use_ocr: true
use_ocr_raw: true
use_page: true
